### ISSUE TITLE
Feature Request: Add Dark Mode to the Website

### ISSUE THREAD

**Issue by anushkaa-dubey** [Mohit5Upadhyay/realTimeTrackingApplication#32]
I would like to contribute to this project by implementing a dark mode feature. This would give users the option to switch between light and dark themes, enhancing the overall user experience, especially in low-light conditions.
Please assign this task to me under gssoc- ext and hacktoberfest

**Comment by AnshuWorld** [comment]
Please assign me this task under gssoc24 extd
